name: Build Docker
on:
  push:
    tags:
      - "*"
    paths:
      - ".github/workflows/docker.yml"

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      ## 设置时区
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      ## 检出工程
      - uses: actions/checkout@v3

      ## 构建镜像
      - run: docker build . -t eframework/yapi:latest

      ## 登录账号
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.EF_DOCKER_USER }}
          password: ${{ secrets.EF_DOCKER_SECRECT }}

      ## 发布镜像
      - run: docker push eframework/yapi:latest
