name: Build Docker
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      ## 设置时区
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      ## 检出工程
      - uses: actions/checkout@v3

      ## 获取版本
      - run: |
          VERSION=$(node -p "require('./package.json').version")  
          echo "Package version is $VERSION"  
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      ## 构建镜像
      - run: docker build . -t eframework/yapi:v${PACKAGE_VERSION}
      - run: docker tag eframework/yapi:v${PACKAGE_VERSION} eframework/yapi:latest

      ## 登录镜像
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.EF_DOCKER_USER }}
          password: ${{ secrets.EF_DOCKER_TOKEN }}

      ## 发布镜像
      - run: docker push eframework/yapi:v${PACKAGE_VERSION}
      - run: docker push eframework/yapi:latest
